name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: npm ci
        name: Install modules from npm
      - run: npm test
        name: Run the tests
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: npm ci
        name: Install modules from npm
      - run: npm run build
        name: Build the application
      - uses: actions/upload-artifact@v3 
        name: archive coverage report
        with:
        name: build-folder
        path: dist
  coverage:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout respository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
    - run: npm ci
      name: Install modules from npm
    - run: npm test -- --coverage
    - uses: actions/upload-artifact@v3 
      name: archive coverage report
      with:
        name: coverage-report
        path: coverage